name: bd_calling_task
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

#---Main Dependencies---#
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  logger: ^2.4.0
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.2.0+3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  connectivity_plus: ^5.0.2

#---Dev Dependencies---#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

#---Flutter---#
flutter:
  uses-material-design: true

  assets:
    - .env
